# Generated by Django 5.1.9 on 2025-07-27 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=128, unique=True)),
                ("description", models.CharField(max_length=1024, null=True)),
                ("start_time", models.DateTimeField(unique=True)),
                ("end_time", models.DateTimeField(unique=True)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="speakers.speaker",
                    ),
                ),
            ],
        ),
    ]
