# Generated by Django 5.1.9 on 2025-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0001_initial"),
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talk",
            name="speaker",
        ),
        migrations.AddField(
            model_name="talk",
            name="speakers",
            field=models.ManyToManyField(related_name="talks", to="speakers.speaker"),
        ),
    ]
