# Generated by Django 5.1 on 2025-07-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_remove_talk_speaker_talk_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='activity_type',
            field=models.CharField(choices=[('WS', 'Workshop'), ('PR', 'Presentation')], default='PR', max_length=2),
        ),
    ]
