# Generated by Django 5.1 on 2025-07-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_sponsor_talk_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('SP', 'Sponsor'), ('PR', 'Partner')], default='SP', max_length=2),
        ),
    ]
