# Generated by Django 5.1.9 on 2025-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0005_sponsor_sponsor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="mode",
            field=models.CharField(
                choices=[("ON", "Online"), ("IP", "In Person")],
                default="IP",
                max_length=2,
            ),
        ),
    ]
