# Generated by Django 5.1 on 2025-07-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_type',
        ),
    ]
