# Generated by Django 5.1.9 on 2025-07-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0006_remove_sponsor_sponsor_type"),
        ("talks", "0006_talk_mode"),
    ]

    operations = []
