# nginx/nginx.conf

upstream saphira_app {
    server saphira-api-prod:8000;
}

server {
    listen 80;
    server_name saphira.semanadesi.com www.saphira.semanadesi.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }

}

server {

    listen 443 ssl;
    server_name saphira.semanadesi.com www.saphira.semanadesi.com;

    ssl_certificate /etc/letsencrypt/live/saphira.semanadesi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/saphira.semanadesi.com/privkey.pem;

    location /static/ {
        alias /app/static/;
    }

    location / {
        proxy_pass http://saphira_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

}
