# Generated by Django 5.1.9 on 2025-07-17 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=128, unique=True)),
                (
                    "usp_number",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
            ],
        ),
    ]
