# Generated by Django 5.1.9 on 2025-07-27 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0001_initial"),
        ("winners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawwinner",
            name="talk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talks.talk"
            ),
        ),
    ]
