# Generated by Django 5.1.9 on 2025-07-21 05:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256, null=True)),
                ('min_presence', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
