# Generated by Django 5.1 on 2025-05-22 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_time_talk_end_time_talk_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('social_media', models.CharField(max_length=128, null=True)),
                ('pronouns', models.CharField(max_length=32, null=True)),
                ('role', models.CharField(max_length=64)),
            ],
        ),
    ]
