# Generated by Django 5.1 on 2025-06-04 00:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talk')),
            ],
            options={
                'unique_together': {('student', 'talk')},
            },
        ),
    ]
