# Generated by Django 5.1 on 2025-06-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_drawwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.speaker'),
        ),
    ]
