# Generated by Django 5.1.9 on 2025-07-24 02:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512, null=True)),
                ('social_media', models.CharField(max_length=64, null=True)),
                ('pronouns', models.CharField(max_length=16, null=True)),
                ('role', models.CharField(max_length=64)),
            ],
        ),
    ]
