# Generated by Django 5.1.9 on 2025-08-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speaker",
            old_name="social_media",
            new_name="instagram_link",
        ),
        migrations.AddField(
            model_name="speaker",
            name="linkedin_link",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
