# Generated by Django 5.1.9 on 2025-07-27 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_studentgift"),
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="talks.talk"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "talk")},
            },
        ),
    ]
