# Generated by Django 5.1.9 on 2025-05-20 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gift_studentgift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='date_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='talk',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
