# Generated by Django 5.1.9 on 2025-06-11 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_talk_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='min_presence',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gift',
            name='total_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
