# Generated by Django 5.1.9 on 2025-07-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_gift_min_presence_alter_gift_total_amount"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="drawwinner",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="studentgift",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
