# Generated by Django 5.1.9 on 2025-07-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_presence_student_alter_drawwinner_student_and_more"),
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgift",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gifts.gift"
            ),
        ),
        migrations.DeleteModel(
            name="Gift",
        ),
    ]
