# Generated by Django 5.1.9 on 2025-07-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_studentgift_gift_delete_gift'),
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.speaker'),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
