# Generated by Django 5.1.9 on 2025-07-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_talk_speaker_delete_speaker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DrawWinner",
        ),
    ]
