# Generated by Django 5.1.9 on 2025-07-27 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_drawwinner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGift',
        ),
    ]
