# Generated by Django 5.1 on 2025-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_drawwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='activityType',
            field=models.CharField(choices=[('WS', 'Workshop'), ('PR', 'Presentation')], default='PR', max_length=2),
        ),
    ]
