# Generated by Django 5.1 on 2025-07-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_talk_activitytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='activityType',
            new_name='activity_type',
        ),
    ]
