# Generated by Django 5.1.9 on 2025-07-27 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_talk_speaker"),
        ("talks", "0001_initial"),
        ("winners", "0002_alter_drawwinner_talk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="talk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talks.talk"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="talk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talks.talk"
            ),
        ),
        migrations.DeleteModel(
            name="Talk",
        ),
    ]
