# Generated by Django 5.1.9 on 2025-07-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_delete_studentgift"),
        ("api", "0015_alter_presence_talk_alter_token_talk_delete_talk"),
    ]

    operations = []
