# Generated by Django 5.1.9 on 2025-07-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_merge_20250727_1339"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Presence",
        ),
    ]
