# Generated by Django 5.1.9 on 2025-07-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_presence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
